"""empty message

Revision ID: 4a894fa873ed
Revises: 652f92c9c43e
Create Date: 2024-10-09 00:11:22.506762

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from enums.languages_type import LanguagesType


# revision identifiers, used by Alembic.
revision = '4a894fa873ed'
down_revision = '652f92c9c43e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    languages_enum = postgresql.ENUM('EN', 'FR', name='languagestype')
    languages_enum.create(op.get_bind())
    op.add_column('users', sa.Column('language', sa.Enum(LanguagesType, name='languagestype'), nullable=False, server_default='FR'))
    
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'language')    
    languages_enum = postgresql.ENUM('EN', 'FR', name='languagestype')
    languages_enum.drop(op.get_bind())

    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'language')
    # ### end Alembic commands ###
