"""add sso_user_id user table

Revision ID: 652f92c9c43e
Revises: d14fa84b3aa5
Create Date: 2024-06-25 15:15:15.868696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '652f92c9c43e'
down_revision = 'd14fa84b3aa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sso_user_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sso_user_id')
    # ### end Alembic commands ###
