"""empty message

Revision ID: ae2655158b67
Revises: 4fd853a1225b
Create Date: 2025-05-29 02:16:10.283288

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ae2655158b67'
down_revision = '4fd853a1225b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE audits
        ALTER COLUMN timestamp
        TYPE TIMESTAMP
        USING timestamp::timestamp
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audits', 'timestamp',
        type_=sa.String())
    # ### end Alembic commands ###
