version: "3.8"

services:
  front:
    build: ./front
    volumes:
      - ./front:/front
    restart: always
    ports:
      - 3000:3000
    image: front_i
    container_name: front

  api:
    build: ./api
    volumes:
      - ./api:/api
    command: uvicorn main:app --reload --host 0.0.0.0
    restart: always
    hostname: 0.0.0.0
    environment:
      - 127.0.0.1
    ports:
      - 8000:8000
    image: api_i
    container_name: api

  # db:
  #   container_name: database
  #   image: 'mariadb:latest'
  #   restart: always
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - './.docker/mysql:/var/lib/mysql'
  #   environment: 
  #     MARIADB_ROOT_PASSWORD: admin

