services:
  # front:
  #   build: 
  #     context: ./front
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   image: front_i
  #   container_name: front
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - ./front:/front
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true

  api:
    build: ./api
    volumes:
      - ./api:/api
    command: uvicorn main:app --reload --host 0.0.0.0
    restart: always
    hostname: 0.0.0.0
    environment:
      SSO_ADMIN_USERNAME: admin
      SSO_ADMIN_PASSWORD: admin
      SSO_URL: http://host.docker.internal:8080/
      SSO_REALM: local
      SSO_CLIENT_ID: client
      WWW_URL: http://localhost:3000
      DATABASE_URL: postgresql://admin:admin@keycloak-db:5432/admin
      TIMEZONE: America/Toronto
    ports:
      - 8000:8000
    image: api_i
    container_name: api
    stdin_open: true
    depends_on:
      - db
      - keycloak-server
      - keycloak-db

  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'admin'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d admin"]
      interval: 30s
      timeout: 30s
      retries: 3

  keycloak-server:
    build: ./sso
    ports:
      - 8080:8080
      - 8443:8443
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_ADDR=keycloak-db
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_SCHEMA=keycloak
      - DB_USER=admin
      - DB_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak-db/keycloak
      - KC_DB_USERNAME=admin
      - KC_DB_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KC_HOSTNAME_STRICT_BACKCHANNEL=false
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT_HTTPS=false
      - PROXY_ADDRESS_FORWARDING=true
    depends_on:
      keycloak-db:
        condition: service_healthy

  keycloak-db:
    image: postgres:16
    ports:
      - 5433:5432
    volumes:
      - 'postgres_keycloak_db:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'keycloak'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d keycloak"]
      interval: 30s
      timeout: 30s
      retries: 3
  
  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  postgres_keycloak_db:
    driver: local
  postgres:
    driver: local