FROM node:lts-alpine

WORKDIR /front

COPY ./package.json ./
COPY ./package-lock.json ./

RUN npm install

COPY . .

EXPOSE 3000
ENV CHOKIDAR_USEPOLLING=true

CMD ["npm", "run", "start"]